### ISSUE TITLE
Toy example in docs doesn't pass pyhf inspect

### ISSUE THREAD

**Issue by matthewfeickert** [diana-hep/pyhf#489] opened 2019-06-25 15:54 UTC
# Description

The [toy example in the docs](https://github.com/diana-hep/pyhf/blob/4869a15b8715e6d446428489f1fa33de96579e6c/docs/likelihood.rst#toy-example) needs to be updated as it doesn't pass `pyhf inspect`. It needs to use the new (as of PR #488) "observations" instead of "data" and is missing a version.

# Expected Behavior

```
$ pyhf inspect toy_example.json
          Summary       
    ------------------  
       channels  1
        samples  2
     parameters  2
      modifiers  2

       channels  nbins
     ----------  -----
  singlechannel    2  

        samples
     ----------
     background
         signal

     parameters  constraint              modifiers
     ----------  ----------              ----------
             mu  unconstrained           normfactor
uncorr_bkguncrt  constrained_by_poisson  shapesys

    measurement           poi            parameters
     ----------        ----------        ----------
(*) Measurement            mu            (none)

```

# Actual Behavior

```
$ pyhf inspect toy_example.json
Traceback (most recent call last):
  File "/home/mcf/Code/GitHub/pyhf/pyhf/utils.py", line 53, in validate
    return validator.validate(spec)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/jsonschema/validators.py", line 348, in validate
    raise error
jsonschema.exceptions.ValidationError: Additional properties are not allowed ('data' was unexpected)

Failed validating 'additionalProperties' in schema:
    {'$id': 'https://diana-hep.org/pyhf/schemas/1.0.0/workspace.json',
     '$schema': 'http://json-schema.org/draft-06/schema#',
     'additionalProperties': False,
     'properties': {'channels': {'items': {'$ref': 'defs.json#/definitions/channel'},
                                 'type': 'array'},
                    'measurements': {'items': {'$ref': 'defs.json#/definitions/measurement'},
                                     'type': 'array'},
                    'observations': {'items': {'$ref': 'defs.json#/definitions/observation'},
                                     'type': 'array'},
                    'version': {'const': '1.0.0'}},
     'required': ['channels', 'measurements', 'observations', 'version'],
     'type': 'object'}

On instance:
    {'channels': [{'name': 'singlechannel',
                   'samples': [{'data': [5.0, 10.0],
                                'modifiers': [{'data': None,
                                               'name': 'mu',
                                               'type': 'normfactor'}],
                                'name': 'signal'},
                               {'data': [50.0, 60.0],
                                'modifiers': [{'data': [5.0, 12.0],
                                               'name': 'uncorr_bkguncrt',
                                               'type': 'shapesys'}],
                                'name': 'background'}]}],
     'data': {'singlechannel': [50, 60]},
     'measurements': [{'config': {'parameters': [], 'poi': 'mu'},
                       'name': 'Measurement'}]}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mcf/venvs/pyhf-dev/bin/pyhf", line 11, in <module>
    load_entry_point('pyhf', 'console_scripts', 'pyhf')()
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mcf/venvs/pyhf-dev/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/mcf/Code/GitHub/pyhf/pyhf/commandline.py", line 116, in inspect
    w = Workspace(wspec)
  File "/home/mcf/Code/GitHub/pyhf/pyhf/pdf.py", line 490, in __init__
    utils.validate(self.spec, self.schema, version=self.version)
  File "/home/mcf/Code/GitHub/pyhf/pyhf/utils.py", line 55, in validate
    raise InvalidSpecification(err)
pyhf.exceptions.InvalidSpecification: Additional properties are not allowed ('data' was unexpected).
	Path: 
	Instance: {'channels': [{'name': 'singlechannel', 'samples': [{'name': 'signal', 'data': [5.0, 10.0], 'modifiers': [{'name': 'mu', 'type': 'normfactor', 'data': None}]}, {'name': 'background', 'data': [50.0, 60.0], 'modifiers': [{'name': 'uncorr_bkguncrt', 'type': 'shapesys', 'data': [5.0, 12.0]}]}]}], 'data': {'singlechannel': [50, 60]}, 'measurements': [{'name': 'Measurement', 'config': {'poi': 'mu', 'parameters': []}}]}
```

# Checklist

- [x] Run `git fetch` to get the most up to date version of `master`
- [x] Searched through existing Issues to confirm this is not a duplicate issue
- [x] Filled out the Description, Expected Behavior, Actual Behavior, and Steps to Reproduce sections above or have edited/removed them in a way that fully describes the issue

**Comment by matthewfeickert** [comment] 2019-06-25 16:21
Bringing the [discussion into the Issue](https://github.com/diana-hep/pyhf/pull/490#issuecomment-505516257).

> Should we try to ship some toy examples as part of the `MANIFEST.in`? This way we could also test this and catch regressions. One way I'm looking at this is that (similar to `pyhf.simplemodels`) shipping some demo workspaces might help with onboarding, but yeah they might not need to be in a release but could instead be in the docs. (I just know that a *lot* of people are happily using the HistFitter demo scripts as a baseline which they adapt.

@lukasheinrich This seems fine to me, given that adding one or two JSON files is negligible in size. @kratsg Do you have any issues/thoughts with/on this?

**Comment by kratsg** [comment] 2019-06-25 20:44
btw, this is relatively fixed by having doctesting for the toy example.

**Comment by kratsg** [comment] 2019-06-25 20:44
> one way I'm looking at this is that (similar to pyhf.simplemodels) shipping some demo workspaces might help with onboarding, but yeah they might not need to be in a release but could instead be in the docs. (I just know that a *lot* of people are happily using the HistFitter demo scripts as a baseline which they adapt.

Put these examples directly in the docs. If we provide them as files, etc... this encourages bad habits. We want people to be _actively_ copying, instead of passively copying.

**Comment by matthewfeickert** [comment] 2019-06-25 20:54
> btw, this is relatively fixed by having doctesting for the toy example.

Won't this required additional code that doctest runs to evaluate the example? I would think that we would just want to show the example JSON and not additional stuff, which is why I created the separate file and the pytest test in the PR.

> Put these examples directly in the docs. If we provide them as files, etc... this encourages bad habits. We want people to be actively copying, instead of passively copying.

That's fine. Where do you want the files then?

**Comment by kratsg** [comment] 2019-06-25 21:17
But there's no reason we have to show _only_ the example JSON, but also an example of how one can run it, no? The problem is that by putting the example in one location and the test in another, it decouples the two more.

**Comment by matthewfeickert** [comment] 2019-06-25 21:35
> But there's no reason we have to show _only_ the example JSON, but also an example of how one can run it, no? 

I guess. Though this seems like the point of the example notebooks as opposed to the spec docs.

> The problem is that by putting the example in one location and the test in another, it decouples the two more.

I understand what you mean, but this decoupling seems slight to me given that I currently have it rendered in the docs with `literalinclude`. If we were going to do this in doctest then I think that the most illustrative example would be to run `pyhf inspect` (as I do now in the test). Do you know how to run shell code in Sphinx's doctest without [having to do this](https://bskinn.github.io/Testing-CLI-Scripts/)? I know that we can do it with `shlex`, but we don't want to show that in the docs as that isn't how a user would normally test their JSON.

**Comment by kratsg** [comment] 2019-06-25 21:42
> I understand what you mean, but this decoupling seems slight to me given that I currently have it rendered in the docs with `literalinclude`. If we were going to do this in doctest then I think that the most illustrative example would be to run `pyhf inspect` (as I do now in the test). Do you know how to run shell code in Sphinx's doctest without [having to do this](https://bskinn.github.io/Testing-CLI-Scripts/)? I know that we can do it with `shlex`, but we don't want to show that in the docs as that isn't how a user would normally test their JSON.

Good point. My biggest concern atm is we remove the `literalinclude` from the docs at some point later but the test remains -- or vice-versa... and neither really will affect the other and we start code rot.

**Comment by matthewfeickert** [comment] 2019-06-26 04:13
> My biggest concern atm is we remove the `literalinclude` from the docs at some point later but the test remains -- or vice-versa... and neither really will affect the other and we start code rot.

Sure. I don't really know how to resolve this though, beyond putting a comment in above the `literalinclude` that says if you're going to touch the below go update the following tests. Though no one would say that's robust.

**Comment by matthewfeickert** [comment] 2019-06-26 04:13
@kratsg Do you have thoughts on _where_ these files should live? If you don't think they should be included in the manifest then they can't be under `pyhf` as that causes `check-manifest` to fail.

```
$ check-manifest || travis_terminate 1
lists of files in version control and sdist do not match!
missing from sdist:
  pyhf/examples/2-bin_single-channel.json
suggested MANIFEST.in rules:
  recursive-include pyhf *.json
```

I guess they could live under the `docs`? Maybe `docs/examples/JSON/`?

**Comment by kratsg** [comment] 2019-06-26 04:28
Why can't they go under the `examples/` we already have?

**Comment by matthewfeickert** [comment] 2019-06-26 04:30
> Why can't they go under the `examples/` we already have?

Oops! They totally can. Sorry, that's where we used to have the notebooks and I thought that directory was just a remnant on my local machine that hadn't gotten cleaned away yet. I'll move them there.

**Closed** 2019-06-26 05:35 UTC
Labels: bug, docs
